import numpy as np
import scipy.stats as stats

def cast_straws_to_curve(curve_pts, origin, num_straws=1000):
    """
    Casts radial ray 'straws' from an interior origin to find intersection distances.
    Simulates omnidirectional probabilistic sampling across the Jordan curve boundary.
    """
    angles = np.linspace(-np.pi, np.pi, num_straws, endpoint=False)
    straw_lengths = []

    # Center the curve points on the ray origin for angular computation
    centered_curve = curve_pts - origin
    curve_angles = np.arctan2(centered_curve[:, 1], centered_curve[:, 0])
    curve_distances = np.linalg.norm(centered_curve, axis=1)

    for alpha in angles:
        # Find closest angular match in the discrete boundary matrix
        # Unwraps the boundary topology relative to the ray projection angle
        angle_diff = np.abs(curve_angles - alpha)
        angle_diff = np.minimum(angle_diff, 2 * np.pi - angle_diff)
        closest_idx = np.argmin(angle_diff)

        straw_lengths.append(curve_distances[closest_idx])

    return np.array(straw_lengths)

def compute_distribution_metrics(lengths, num_bins=50):
    """
    Extracts 2D statistical signatures from the chord-length distributions
    to capture structural complexity and chaotic randomness.
    """
    variance = np.var(lengths)
    skewness = stats.skew(lengths)
    kurtosis = stats.kurtosis(lengths) # Measures tail-heaviness / pocket density

    # Compute Shannon Entropy of the histogram distribution
    hist, _ = np.histogram(lengths, bins=num_bins, density=True)
    hist = hist[hist > 0] # Remove zero bins to avoid log(0) errors
    entropy = -np.sum(hist * np.log2(hist))

    return {
        "Variance": variance,
        "Skewness": skewness,
        "Kurtosis": kurtosis,
        "Shannon_Entropy": entropy
    }

if __name__ == "__main__":
    print("[18_statistical_analyzer] Initializing data analysis pipeline...")

    # 1. Load the boundary matrices generated by script 17
    try:
        sharp_curve = np.load('17_sharp_curve.npy')
        rounded_curve = np.load('17_rounded_curve.npy')
    except FileNotFoundError:
        print(" Error: Source matrices not found. Please run 17_hybrid_generator.py first.")
        exit(1)

    # 2. Establish a unified interior origin point (the spatial center of the square box base)
    # Origin is set to (0.5, 0.5) to sample all boundaries uniformly
    origin = np.array([0.5, 0.5])

    # 3. Process the straws (Simulating 1,440 radial inspections)
    num_straws = 1440
    sharp_lengths = cast_straws_to_curve(sharp_curve, origin, num_straws=num_straws)
    rounded_lengths = cast_straws_to_curve(rounded_curve, origin, num_straws=num_straws)

    # 4. Extract statistical profiles
    sharp_metrics = compute_distribution_metrics(sharp_lengths)
    rounded_metrics = compute_distribution_metrics(rounded_lengths)

    # 5. Output Diagnostic Comparison
    print("\n========================================================")
    print("      STRUCTURAL TAXONOMY STATISTICAL SIGNATURES       ")
    print("========================================================")
    print(f"Metric            | Pure Sharp Fractal | Rounded Variant")
    print("-------------------|--------------------|-------------------")
    for metric in sharp_metrics.keys():
        s_val = sharp_metrics[metric]
        r_val = rounded_metrics[metric]
        print(f"{metric:<18} | {s_val:<18.5f} | {r_val:<18.5f}")
    print("========================================================")

    # Interrogate the randomness outcome
    entropy_delta = abs(sharp_metrics["Shannon_Entropy"] - rounded_metrics["Shannon_Entropy"])
    print(f"\n[Diagnostic Insight] Shannon Entropy Shift: {entropy_delta:.5f}")
    if entropy_delta < 0.15:
        print(" -> CRITICAL OUTCOME: Randomness is RETAINED.")
        print("    The structural layout and spatial frequency drive the chaos, not the sharp corners!")
    else:
        print(" -> ALTERNATE OUTCOME: Randomness is REDUCED.")
        print("    The observed chaos was primarily driven by sharp, non-differentiable boundary cusps.")
